### ISSUE TITLE
Broken output for compressed input

### ISSUE THREAD

**Issue by pepelsbey** [terrierscript/cssjoin#11]
## Steps to reproduce

Create `screen.css` with following content (which is already compressed)

```
@import 'blah.css';p { width:1px;height:1px }
```

Content of `blah.css` is

```
p { color:#FFF }
```

Run `cssjoin screen.css`
## Expected output

```
p { color:#FFF }p { width:1px;height:1px }
```
## Actual output

```
p { color:#FFF }
height:1px }
```

**Comment by suisho** [comment]
Thank you for issue reporting.
But sorry I'm so busy because of my works... Please wait or pull request if you can.

**Comment by suisho** [comment]
fixed

**Comment by pepelsbey** [comment]
Thank you!
