### ISSUE TITLE
Sass/scss support

### ISSUE THREAD

**Issue by terkelg** [terrierscript/cssjoin#9]
Is it possible to add support for files with the .scss/.sass extension?

**Comment by suisho** [comment]
Sorry, but I will not support.

I think `cssjoin` should limit the resolving scope. 
This thinking is follow the unix philothophy (Make each program do one thing well).

In the first place, this project's first motivation is lesscss not support css importing function, and I want resolve the problem for generally.

All css meta language (scss/sass/less) files is coverted to css for anything in the world, and `cssjoin`'s apploach is convert those **compiled css file**.

And recently, developed some build systems ( grunt, gulp and others).
If you want use `cssjoin' with sass file, you should use those build systems (like scss => css => cssjoined-css).

And I provide [gulp-cssjoin](https://github.com/suisho/gulp-cssjoin) or [grunt-cssjoin](https://github.com/suisho/grunt-cssjoin). please use it if you need.

**Comment by frontier777** [comment]
If it is just the file extension and not any scss/sass/less processing (ie. just using cssjoin for concatenation & resolving paths) then you could do that by just removing this one block, in the function getReplaceMap(css, resolvePaths), which is found in lib/util.js:

```
/*
    if(/\.css$/.test(fileName) === false){
      continue;
    }
*/
```

(that is what is forcing the .css extension to be the only allowed extension)

**Comment by terkelg** [comment]
@suisho I understand, and I appreciate your work.
@frontier777 thanks a lot, that's exactly what I needed.

**Comment by suisho** [comment]
@terkelg Sorry my poor understanding... :shit:

But I cannot why need skip extention check.
I think that occur some unintended behavor ( for example, include raw scss file and broken css file)

**Comment by terkelg** [comment]
I have multiple scss files I want to concatenate, but without compiling them. 
I'm actually trying to find a way to reproduce the sass @import functionality, but without actually compiling to css. The reason is that I'm working on a Shopify Theme, which support raw scss files, except the @import function sadly - which I then have to do locally. That's why I want to skip extension check, and include raw scss files so that I get one joined scss file ready for upload :smile:

**Comment by suisho** [comment]
Sorry I don't know Shopify Theme.
Are you need scss file? (is that problem not resolve use compiled css?)

If you need, I can approve this function as optionally ( for example, include extension option )

**Comment by frontier777** [comment]
I don't think forcing the extension to be .css is really necessary. In my opinion any format that is similar enough to use the @import syntax should be treated the same way, ie. concat & resolve url() references within.

**Comment by suisho** [comment]
@frontier777 
Some dirty ( or legacy) css include dynamic css files ( like php file) and if import local php file, that make many sadness. 
I think forcing extension is necessary and I am no going to change default behavior.

**Comment by frontier777** [comment]
@suisho 
That's a good point! Personally I would only use a tool like this for pre-processing static resources. I don't use the @import rule in production at all, but it's an awesome way to work in development and feed this file directly into a tool chain (starting with cssjoin) to minify.:-)

**Comment by frontier777** [comment]
Could add a whitelist of css-compatible file extensions to the regex I suppose. Before I found cssjoin I hoped to use LESS (similar to SASS) but it required an extra declaration on the import statement, which broke the source.css in the browser..

http://stackoverflow.com/questions/23735535/command-line-tool-to-inline-css-import-statements-and-resolve-relative-url-refer

**Comment by suisho** [comment]
@terkelg I think your issue once again.
Are you resolve problem with below solution?
1. Remove all @import syntax in scss files.
2. Concat scss files with like grunt-concat
3. Upload concatenated scss file.
